language: go

sudo: false

go:
  - 1.3
  - 1.4
  - tip

install:
  # Install our tracked dependencies
  - go get github.com/tools/godep
  - godep restore
  - go get gopkg.in/mgo.v2
  - go get gopkg.in/mgo.v2/bson
  - go get golang.org/x/text/collate
  - go get golang.org/x/text/language

  # Google App Engine dependencies
  - cd ..
  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.19.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.19.zip
  - export PATH=$PATH:$PWD/go_appengine/
  - cd cayley

script:
  - go test -v ./...
  - goapp test -v ./graph/gaedatastore

